### ISSUE TITLE
Memory problems

### ISSUE THREAD

**Issue by TomasWilson** [Earlh21/TaintedCainCrafter#2]
Hey, I went through your project a bit (mostly for me as a learning experience, I often struggle with reading foreign code)

I found a huge (I'm talking HUGE) issue, that massively affects performance and memory consuption. (Especially the latter)

When running, there are massive amounts of pickup objects in existance. For example, if you add one pickup to ~20 of the possible pickups, more than 1,000,000 pickup objects are in existance.

The Heap size is ~1.3GB at that point.

Here is the problem with that:
EVERY SINGLE Pickup object loads and stores its respective BitmapImage. Thats a few hundred bytes per object, massively inflating memory consumption. I have commented out the line that loads images for pickups. Obviously, you cant see them in the application at that point, but the application seems to otherwise operate normally.

I have tried the same szenario as mentioned above
The Heap size is ~84MB at that point. 

Best regards.

**Comment by Earlh21** [comment]
Thanks for noticing this, I completely overlooked it. Should be fixed now; pickups now store a reference to their images in a static array instead of an instance each.
