### ISSUE TITLE
Search on crafter not working

### ISSUE THREAD

**Issue by Eegeg** [Earlh21/TaintedCainCrafter#3]
when you try to search something on the crafter it wont show the item even if its not blacklisted but it works on the highlighter
![image](https://user-images.githubusercontent.com/88250823/141036484-3759d616-ace7-4f24-a849-7228765f1798.png)
![image](https://user-images.githubusercontent.com/88250823/141036691-f50fd79e-7ac1-4c7b-be15-c2392b352272.png)
![image](https://user-images.githubusercontent.com/88250823/141036725-cb701905-649d-460e-966e-d2ca2dcf03ee.png)

**Comment by laquazi** [comment]
I believe it only shows the items you can craft given the pickups you have. This search bar is only useful if you have too many options to craft and you can not find the one you need.

**Comment by Earlh21** [comment]
Markov99 has it right. Enter some pickups to see items.
