### ISSUE TITLE
Item description seems to be broken

### ISSUE THREAD

**Issue by xiorcal** [Earlh21/TaintedCainCrafter#6]
Hi, 

where it should be a descrption of an item all I see is #NAME_OF_ITEM

![image](https://user-images.githubusercontent.com/2391639/182141104-c24bff40-10c4-430d-8e12-0d829bd6215b.png)
![image](https://user-images.githubusercontent.com/2391639/182141138-7bf7d674-226b-41f1-9b72-f3f6c91bfc7f.png)

I don't know if the behavior is intentionnal or not but it seems buggy to me 😅.

Have a nice day :)

**Comment by Earlh21** [comment]
This has been fixed for a while, just hasn't been included in a new release. I just put out a release that includes the names and descriptions.
