### ISSUE TITLE
[Feature] Group by Highlight, more Highlight colors

### ISSUE THREAD

**Issue by akatechis** [Earlh21/TaintedCainCrafter#8]
Would be nice to have a feature such that if any craftable items are highlighted, the appear near the top and are grouped together. Would make it easier for me to make a decision which items to craft given a bunch of consumables.

In my specific case, I have break-items highlighted green (those come first), then a bunch of tears, dmg, effects items for power are highlighted blue, and everything else is unmarked. If there were more colors, I could mark defensive/health items as another color, and then utility items like flight or transformation items yet another color.

**Comment by Earlh21** [comment]
Done, and added more colors.
